
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reservation
{

    public int Id { get; set; }

    public int ClientId { get; set; }

    public int BookId { get; set; }

    public int Interval { get; set; }

    public int GivenBy { get; set; }

    public System.DateTime GivenAt { get; set; }

    public Nullable<int> TakenBackBy { get; set; }

    public Nullable<System.DateTime> TakenBackAt { get; set; }

    public Nullable<decimal> Penalty { get; set; }

    public Nullable<int> BookStatus { get; set; }

    public string Comment { get; set; }



    public virtual Case Case { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Client Client { get; set; }

    public virtual Book Book { get; set; }

}

}
